use std::collections::HashMap;

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

use crate::config::KeyBindings;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    Down,
    Up,
    PageDown,
    PageUp,
    Top,
    Bottom,
    NextTab,
    PrevTab,
    TabByIndex(u8),
    Activate,
    Enqueue,
    Back,
    JumpRoots,
    SourceJump(String),
    PlayPause,
    NextTrack,
    PrevTrack,
    Stop,
    Refresh,
    ToggleThumb,
    /// Cycle to the next registered source mode (Local → Spotify → SomaFm →
    /// Radio, skipping unconfigured). Rebuilds tab list and theme palette.
    CycleSource,
    VolumeUp,
    VolumeDown,
    SetVolume(u8),
    FocusSearch,
    FocusCommand,
    ToggleHelp,
    /// Toggle the dedicated synced-lyrics view over the body area. `B` by
    /// default. Lyrics come from lrclib for any source with track metadata.
    ToggleLyrics,
    ToggleLike,
    OpenDevicePicker,
    TransferToSelectedDevice,
    ToggleShuffle,
    CycleRepeat,
    OpenSortModal,
    ApplySelectedSort,
    /// Scroll the active list to the row that's currently playing. No-op
    /// when the playing track isn't in the active view.
    FollowPlaying,
    /// Empty the queue and stop the active source. Bound to `C` by default;
    /// also runnable as `:clear` from the command bar.
    ClearQueue,
    /// Begin substring filter input on the active list. `Esc` cancels,
    /// `Enter` commits.
    FilterInPage,
    /// Remove the row under the cursor from the Queue. No-op on other tabs.
    RemoveFromQueue,
    /// Expand the cover-art of the row currently under the cursor to a
    /// centered overlay. Triggered by `V` (view). Closed by any key/click.
    ExpandHoveredArt,
    /// Toggle the now-playing art panel between full size and collapsed
    /// (bottom-bar height). `e` by default; mirrors the art-panel click.
    ToggleArtSize,
    /// Open the per-track action menu (like, add-to-queue, pin, go to
    /// album/artist, song radio, add to playlist). `m` by default.
    OpenActionMenu,
    /// Toggle pin state on the hovered row. `P` by default.
    TogglePinHovered,
    /// Download the hovered YouTube track to disk via yt-dlp. `Y` by
    /// default. No-op on non-YouTube rows.
    DownloadHovered,
    /// Seek to a position in the current track, expressed in permille
    /// (0..=1000) so the Action stays Eq/Hash-compatible. Generated by
    /// progress-bar mouse clicks; not bound to any keyboard chord.
    SeekToPermille(u16),
    /// Relative seek in seconds. Negative goes back, positive forward.
    /// Default chords: `H` = -10, `L` = +10.
    SeekRelative(i32),
    None,
}

#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub struct KeyChord {
    pub code: KeyCode,
    pub ctrl: bool,
    pub shift: bool,
    pub alt: bool,
}

impl KeyChord {
    pub fn from_event(ev: KeyEvent) -> Self {
        let mut shift = ev.modifiers.contains(KeyModifiers::SHIFT);
        // crossterm reports Char('A') without SHIFT — normalize so a config
        // binding written as "A" matches whether or not the terminal sets the
        // shift modifier on uppercase letters.
        if let KeyCode::Char(c) = ev.code {
            if c.is_ascii_uppercase() {
                shift = true;
            }
        }
        // crossterm emits Shift+Tab as `KeyCode::BackTab` *with* the SHIFT
        // modifier set, but the binding is just "BackTab" (shift implied).
        // Drop the modifier so the lookup matches the canonical chord.
        if matches!(ev.code, KeyCode::BackTab) {
            shift = false;
        }
        Self {
            code: ev.code,
            ctrl: ev.modifiers.contains(KeyModifiers::CONTROL),
            shift,
            alt: ev.modifiers.contains(KeyModifiers::ALT),
        }
    }
}

#[derive(Debug, Default, Clone)]
pub struct LeaderMap {
    /// Ordered list of (chord, label, action) for stable popup rendering.
    pub entries: Vec<(KeyChord, String, Action)>,
}

impl LeaderMap {
    pub fn lookup(&self, chord: KeyChord) -> Option<&Action> {
        self.entries
            .iter()
            .find(|(c, _, _)| *c == chord)
            .map(|(_, _, a)| a)
    }
}

#[derive(Debug, Default, Clone)]
pub struct Keymap {
    pub bindings: HashMap<KeyChord, Action>,
    pub leaders: HashMap<KeyChord, LeaderMap>,
}

impl Keymap {
    pub fn lookup(&self, chord: KeyChord) -> Option<&Action> {
        self.bindings.get(&chord)
    }

    pub fn leader(&self, chord: KeyChord) -> Option<&LeaderMap> {
        self.leaders.get(&chord)
    }

    pub fn from_config(cfg: &KeyBindings) -> Self {
        let mut bindings = HashMap::new();
        for (action_name, key) in &cfg.global {
            let Some(chord) = parse_chord(key) else {
                tracing::warn!("keybindings.global.{action_name}: invalid key '{key}'");
                continue;
            };
            let Some(action) = parse_action(action_name) else {
                tracing::warn!("keybindings.global: unknown action '{action_name}'");
                continue;
            };
            bindings.insert(chord, action);
        }
        // Arrow-key navigation for users who don't reach for vim keys. The
        // action→key config map holds only one key per action, so these can't
        // live in `default_global`; hardcode them here. `or_insert` means an
        // explicit user binding for the same chord still wins.
        for (code, action) in [
            (KeyCode::Up, Action::Up),
            (KeyCode::Down, Action::Down),
            (KeyCode::Left, Action::Back),
            (KeyCode::Right, Action::Activate),
            (KeyCode::PageUp, Action::PageUp),
            (KeyCode::PageDown, Action::PageDown),
        ] {
            bindings
                .entry(KeyChord {
                    code,
                    ctrl: false,
                    shift: false,
                    alt: false,
                })
                .or_insert(action);
        }
        let mut leaders: HashMap<KeyChord, LeaderMap> = HashMap::new();
        for (leader_key, sub) in &cfg.leaders {
            let Some(leader_chord) = parse_chord(leader_key) else {
                tracing::warn!("keybindings.leaders.{leader_key}: invalid leader chord");
                continue;
            };
            let mut entries: Vec<(KeyChord, String, Action)> = Vec::new();
            for (sub_key, entry) in sub {
                let Some(sub_chord) = parse_chord(sub_key) else {
                    tracing::warn!("keybindings.leaders.{leader_key}.{sub_key}: invalid sub-chord");
                    continue;
                };
                let Some(action) = parse_action(&entry.action) else {
                    tracing::warn!(
                        "keybindings.leaders.{leader_key}.{sub_key}: unknown action '{}'",
                        entry.action
                    );
                    continue;
                };
                entries.push((sub_chord, entry.label.clone(), action));
            }
            entries.sort_by_key(|a| chord_sort_key(&a.0));
            leaders.insert(leader_chord, LeaderMap { entries });
        }
        Self { bindings, leaders }
    }
}

fn chord_sort_key(c: &KeyChord) -> String {
    match c.code {
        KeyCode::Char(ch) => ch.to_string(),
        KeyCode::Enter => "\u{1}enter".into(),
        KeyCode::Esc => "\u{1}esc".into(),
        KeyCode::Tab => "\u{1}tab".into(),
        other => format!("{other:?}"),
    }
}

/// Parse strings like "j", "C-d", "S-Tab", "Enter", "Space", "+", "-".
/// Modifier prefixes: "C-" ctrl, "S-" shift, "A-" alt.
pub fn parse_chord(s: &str) -> Option<KeyChord> {
    let mut ctrl = false;
    let mut shift = false;
    let mut alt = false;
    let mut rest = s;
    loop {
        if let Some(r) = rest.strip_prefix("C-") {
            ctrl = true;
            rest = r;
        } else if let Some(r) = rest.strip_prefix("S-") {
            shift = true;
            rest = r;
        } else if let Some(r) = rest.strip_prefix("A-") {
            alt = true;
            rest = r;
        } else {
            break;
        }
    }
    let code = match rest {
        "Enter" | "Return" => KeyCode::Enter,
        "Esc" | "Escape" => KeyCode::Esc,
        "Tab" => KeyCode::Tab,
        "BackTab" => KeyCode::BackTab,
        "Space" | " " => KeyCode::Char(' '),
        "Backspace" => KeyCode::Backspace,
        "Up" => KeyCode::Up,
        "Down" => KeyCode::Down,
        "Left" => KeyCode::Left,
        "Right" => KeyCode::Right,
        "PageUp" => KeyCode::PageUp,
        "PageDown" => KeyCode::PageDown,
        "Home" => KeyCode::Home,
        "End" => KeyCode::End,
        "Delete" => KeyCode::Delete,
        other if other.chars().count() == 1 => {
            let c = other.chars().next().unwrap();
            if c.is_ascii_uppercase() {
                shift = true;
            }
            KeyCode::Char(c)
        }
        _ => return None,
    };
    Some(KeyChord {
        code,
        ctrl,
        shift,
        alt,
    })
}

pub fn parse_action(s: &str) -> Option<Action> {
    if let Some(rest) = s.strip_prefix("source_jump:") {
        return Some(Action::SourceJump(rest.to_string()));
    }
    if let Some(rest) = s.strip_prefix("tab:") {
        return rest.parse::<u8>().ok().map(Action::TabByIndex);
    }
    Some(match s {
        "quit" => Action::Quit,
        "down" => Action::Down,
        "up" => Action::Up,
        "page_down" => Action::PageDown,
        "page_up" => Action::PageUp,
        "top" => Action::Top,
        "bottom" => Action::Bottom,
        "next_tab" | "next_tab_alt" => Action::NextTab,
        "prev_tab" | "prev_tab_alt" => Action::PrevTab,
        "tab_1" => Action::TabByIndex(0),
        "tab_2" => Action::TabByIndex(1),
        "tab_3" => Action::TabByIndex(2),
        "tab_4" => Action::TabByIndex(3),
        "tab_5" => Action::TabByIndex(4),
        "tab_6" => Action::TabByIndex(5),
        "tab_7" => Action::TabByIndex(6),
        "tab_8" => Action::TabByIndex(7),
        "tab_9" => Action::TabByIndex(8),
        "activate" | "activate_alt" => Action::Activate,
        "enqueue" => Action::Enqueue,
        "back" => Action::Back,
        "back_alt" => Action::Back,
        "jump_roots" => Action::JumpRoots,
        "play_pause" => Action::PlayPause,
        "next_track" => Action::NextTrack,
        "prev_track" => Action::PrevTrack,
        "stop" => Action::Stop,
        "refresh" => Action::Refresh,
        "toggle_thumb" => Action::ToggleThumb,
        "cycle_source" => Action::CycleSource,
        "vol_up" => Action::VolumeUp,
        "vol_down" => Action::VolumeDown,
        "focus_search" => Action::FocusSearch,
        "focus_command" => Action::FocusCommand,
        "toggle_help" => Action::ToggleHelp,
        "toggle_lyrics" => Action::ToggleLyrics,
        "toggle_like" => Action::ToggleLike,
        "open_devices" => Action::OpenDevicePicker,
        "toggle_shuffle" => Action::ToggleShuffle,
        "cycle_repeat" => Action::CycleRepeat,
        "open_sort" => Action::OpenSortModal,
        "follow_playing" => Action::FollowPlaying,
        "clear_queue" => Action::ClearQueue,
        "filter_in_page" => Action::FilterInPage,
        "seek_back" => Action::SeekRelative(-10),
        "seek_forward" => Action::SeekRelative(10),
        "remove_from_queue" => Action::RemoveFromQueue,
        "expand_art" => Action::ExpandHoveredArt,
        "toggle_art_size" => Action::ToggleArtSize,
        "open_action_menu" => Action::OpenActionMenu,
        "toggle_pin" => Action::TogglePinHovered,
        "download_hovered" => Action::DownloadHovered,
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_modifier_chords() {
        let c = parse_chord("C-d").unwrap();
        assert!(c.ctrl);
        assert_eq!(c.code, KeyCode::Char('d'));
        let s = parse_chord("S-Tab").unwrap();
        assert!(s.shift);
        assert_eq!(s.code, KeyCode::Tab);
    }

    #[test]
    fn capital_char_implies_shift() {
        let c = parse_chord("H").unwrap();
        assert!(c.shift);
        assert_eq!(c.code, KeyCode::Char('H'));
    }

    #[test]
    fn parses_source_jump_action() {
        match parse_action("source_jump:spotify").unwrap() {
            Action::SourceJump(s) => assert_eq!(s, "spotify"),
            _ => panic!("wrong action"),
        }
    }

    #[test]
    fn parses_toggle_art_size_action() {
        assert!(matches!(
            parse_action("toggle_art_size"),
            Some(Action::ToggleArtSize)
        ));
    }
}
